1. Import Libraries
2. load_data
3. Head()
4. print nummber or rows and columns
5. information
6. print missing value
7. standerscaleing 
8. drop time column
9. drop duplicate
10. split the data into x and y
11. spint the data into Train_test_split
12. import librires for models and matrix

In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, mean_absolute_error,r2_score,classification_report,confusion_matrix,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier, GradientBoostingClassifier, BaggingClassifier,ExtraTreesClassifier,VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('D:\Intenship\Dataset\creditcard\creditcard.csv')

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
df.drop(['Time'], inplace=True, axis=1)

In [7]:
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [8]:


scaler=StandardScaler()

df['Amount']=scaler.fit_transform(pd.DataFrame(df['Amount']))

In [9]:
df.sample(10)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
178910,2.001924,-0.684268,-1.223001,-0.395680,-0.539162,-1.089972,-0.064350,-0.314606,1.622105,-0.494748,...,0.258915,1.128545,-0.143433,0.199281,0.322250,1.058171,-0.074965,-0.071987,-0.173316,0
232819,1.846853,0.327153,-0.022534,3.686221,0.138142,0.784587,-0.401905,0.328682,-0.618072,1.496569,...,-0.376626,-1.120578,0.538477,0.637053,-0.595940,-0.562567,-0.010777,-0.033810,-0.353229,0
231582,-2.031273,1.767873,-0.101735,-1.168034,0.050816,0.287941,-1.613059,-4.903152,-1.130610,-2.165961,...,-2.891033,-0.502009,0.465608,0.675804,-0.715507,-0.145719,-0.047026,0.040691,-0.189268,0
52791,-2.105287,0.359059,1.696768,-0.447828,-0.709028,-0.220086,-0.020619,0.131411,1.152948,-0.187690,...,0.100817,1.052987,0.340309,0.746038,-0.391841,0.917931,-0.663425,0.060366,-0.259114,0
82057,1.090954,-0.033892,0.500180,0.624507,-0.606979,-0.748956,0.000581,-0.080327,-0.157966,0.093724,...,0.032626,-0.046333,-0.033284,0.562193,0.316384,0.270247,-0.045709,0.016506,-0.108147,0
252030,1.960665,0.067089,-1.644488,1.426861,0.326549,-1.154670,0.641114,-0.387210,0.308403,0.263320,...,0.062698,0.295972,-0.023830,-0.025896,0.420498,-0.490746,-0.026035,-0.057512,-0.179233,0
69435,-0.576102,-0.736941,1.906050,-2.709058,-1.179308,0.122273,-0.314001,0.162965,-2.329949,0.727763,...,-0.056199,-0.083008,0.029870,-0.422835,-0.010053,-0.396894,0.070572,0.096962,0.073406,0
77170,1.262657,0.127627,0.065083,0.093762,-0.371053,-1.312640,0.330532,-0.310045,-0.039163,-0.139004,...,-0.434707,-1.360292,0.193603,0.395966,0.087043,0.620930,-0.106103,0.006734,-0.245321,0
3624,-0.302521,0.447474,-0.495757,-3.214799,2.705041,2.762440,0.593847,0.556451,0.697720,-1.090181,...,0.007343,0.250886,-0.331600,1.009952,0.233730,-0.824471,0.241305,-0.020359,-0.349231,0
213316,1.840882,-0.543399,-1.271718,0.443064,0.065373,-0.186962,0.010568,-0.160279,0.708365,0.015950,...,0.002228,-0.121989,0.077246,0.272048,-0.138270,0.209529,-0.065061,-0.029481,0.158126,0

In [10]:
df.duplicated().sum()

9144

In [11]:
df=df.drop_duplicates()

In [12]:
df.duplicated().sum()

0

In [13]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class'],
      dtype='object')

In [14]:
X=df.drop('Class', axis=1)

y=df['Class']

In [15]:
print(X.shape)  # Should print (284807, 30)
print(y.shape)  # Should print (284807,)

(275663, 29)
(275663,)

In [16]:
X_train,x_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
print(X_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(220530, 29)
(220530,)
(55133, 29)
(55133,)

In [18]:

classifier={

    "LogisticRegression":LogisticRegression(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "AdaBoostClassifier":AdaBoostClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    "BaggingClassifier":BaggingClassifier(),
    "ExtraTreesClassifier":ExtraTreesClassifier(),
    "VotingClassifier":VotingClassifier(estimators= [
                                        ('le',LogisticRegression()),
                                        ('Dc',DecisionTreeClassifier()),
                                        ('RF',RandomForestClassifier()),
                                        ('Ad',AdaBoostClassifier()),
                                        ('GB',GradientBoostingClassifier()),
                                        ('Bc',BaggingClassifier()),
                                        ('EC',ExtraTreesClassifier())
                                                            ],voting='hard')


}

In [19]:
for name, clf in classifier.items():
    print(f"\n=========={name}===========")

    
    clf.fit(X_train, y_train)
    y_pred = clf.predict(x_test)
    
    # Evaluation Metrics
    accuracy = accuracy_score(y_test, y_pred)
    
    
    f1 = f1_score(y_test, y_pred)
    print(f"\n Accuracy: {accuracy}")
    print(f" F1 Score: {f1}")
    
    # Confusion Matrix
    print("\n Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    
    # Classification Report
    print("\n Classification Report:")
    print(classification_report(y_test, y_pred))

==========LogisticRegression===========

 Accuracy: 0.9992200678359603
 F1 Score: 0.718954248366013

 Confusion Matrix:
[[55035     7]
 [   36    55]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.89      0.60      0.72        91

    accuracy                           1.00     55133
   macro avg       0.94      0.80      0.86     55133
weighted avg       1.00      1.00      1.00     55133


==========DecisionTreeClassifier===========

 Accuracy: 0.9989842743910181
 F1 Score: 0.7142857142857142

 Confusion Matrix:
[[55007    35]
 [   21    70]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.67      0.77      0.71        91

    accuracy                           1.00     55133
   macro avg       0.83      0.88      0.86     55133
weighted avg       1.00      1.00      1.00     55133


==========RandomForestClassifier===========

 Accuracy: 0.999419585366296
 F1 Score: 0.8095238095238096

 Confusion Matrix:
[[55033     9]
 [   23    68]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.88      0.75      0.81        91

    accuracy                           1.00     55133
   macro avg       0.94      0.87      0.90     55133
weighted avg       1.00      1.00      1.00     55133


==========AdaBoostClassifier===========

 Accuracy: 0.9991112400921408
 F1 Score: 0.7199999999999999

 Confusion Matrix:
[[55021    21]
 [   28    63]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.75      0.69      0.72        91

    accuracy                           1.00     55133
   macro avg       0.87      0.85      0.86     55133
weighted avg       1.00      1.00      1.00     55133


==========GradientBoostingClassifier===========

 Accuracy: 0.9986033772876499
 F1 Score: 0.37398373983739835

 Confusion Matrix:
[[55033     9]
 [   68    23]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.72      0.25      0.37        91

    accuracy                           1.00     55133
   macro avg       0.86      0.63      0.69     55133
weighted avg       1.00      1.00      1.00     55133


==========BaggingClassifier===========

 Accuracy: 0.9994739992382058
 F1 Score: 0.8242424242424243

 Confusion Matrix:
[[55036     6]
 [   23    68]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.92      0.75      0.82        91

    accuracy                           1.00     55133
   macro avg       0.96      0.87      0.91     55133
weighted avg       1.00      1.00      1.00     55133


==========ExtraTreesClassifier===========

 Accuracy: 0.999492137195509
 F1 Score: 0.8271604938271604

 Confusion Matrix:
[[55038     4]
 [   24    67]]

 Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     55042
           1       0.94      0.74      0.83        91

    accuracy                           1.00     55133
   macro avg       0.97      0.87      0.91     55133
weighted avg       1.00      1.00      1.00     55133


==========VotingClassifier===========